ライブラリの追加
yu20201227/KeepYourFaceGreat pull request #2
Opened 2020-12-08 07:03 UTC by yu20201227

## clone コマンド
git clone https://github.com/yu20201227/KeepYourFaceGreat.git

## Trello
該当のTrelloのチケットの名称を共有
ライブラリの追加
## 概要
ライブラリの追加

## レビューで見て欲しいポイント
テスト段階なので、PRがしっかりとできているか
余計な差分が含まれていないか
## 参考URL

## 11 Pro や SEなど異なる端末でもレイアウトが崩れないか？
別チケット

## 期待通りの挙動をするか
OK 

## レビュー依頼
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741 

レビューお願いしますー！

2020-12-08 14:45 UTC, fuchi0741 commented
cloneコマンドですが、PRのブランチがcloneできるコマンドを記載していただくことはできますか？
今のままではdevelopブランチをcloneすることになるのですが、feature/libraryブランチをクローンできるコマンドを記載して欲しいですー！
レビュー時にローカルにcloneしたいときにコピペで済むので楽なんですよねmm

2020-12-08 14:46 UTC, fuchi0741 commented
チケット追加依頼出しますー！
READMEに使用ライブラリ一覧を作成

チケット作成とどこかのタイミングで実施お願いしますー！

使用するライブラリを把握したいのでー！

2020-12-08 14:57 UTC, fuchi0741 commented on keepYourFaceGreat/ViewController.swift
> -        // Do any additional setup after loading the view.
この差分は削除する必要がないと思うのですが、なんでかわかりますか？

テストのプルリクでも削除していたので、、！
そもそも先ほどのテストのプルリクはマージする予定はなかったのでしょうか？
それであれば今回のコメント削除は理解できますが、、！

わからなかったら聞いてくださいー！

2020-12-08 15:02 UTC, fuchi0741 reviewed
```
.DS_Store
```
```
keepYourFaceGreat.xcodeproj/project.xcworkspace/xcuserdata/owner.xcuserdatad/UserInterfaceState.xcuserstate
```
この2つは実は余計な差分なので、別で対応する必要がありますー！
対応内容は、上記の2つを差分に含めないようにすると言う処理です。

git ignore というワードで調べてみてください！
ちょっとgit関連になってしましますが、、、！頑張りましょう！
別ブランチで対応お願いしますー！今回はとりあえず大丈夫です！

2020-12-08 15:06 UTC, fuchi0741 requested changes

2020-12-08 15:06 UTC, fuchi0741 commented on Podfile
> +pod 'lottie-ios'
ここのインデントがあっていないので修正お願いしますー！

L6のuse...に合わせてください！

ちなみにpodfileはRubyで書かれています

2020-12-08 15:06 UTC, fuchi0741 commented on Podfile
> +# platform :ios, '9.0'
#は Swift でいう // つまりコメントを表しますー！

L1のコメントを読んでみて、L2に適切な処理をお願いしますー！
どこまでこのアプリがiOSのサポートをするのかは任せますー！

わからなかったら質問くださいー！

2020-12-08 15:06 UTC, fuchi0741 commented on Podfile
> +pod 'lottie-ios'
pod xxx の部分ですね

2020-12-08 15:13 UTC, fuchi0741 reviewed
Pods/xxx というファイルが死ぬほどあると思いますが、これも実は余計な差分になりますmm

というのもpodfile.lockがどんなライブラリ(pods/xxx関係)をインストールしているかと管理しているファイルだから、podfile.lockさえあればpods系のファイルはGitHub上で管理をしなくれも問題がないんですよね！

なので、pods 周りは全て余計な差分になるのでGitの管理外にできるように調整をお願いしたいですー！
git ignore 周りですね！

git ignoreは別PR対応で大丈夫です！

2020-12-08 15:14 UTC, fuchi0741 requested changes
@yu20201227 コメントしました！
podfileの修正だけお願いします！

2020-12-08 15:30 UTC, fuchi0741 commented
あ、修正の方法がわからなければ行ってくださいー！

2020-12-08 15:32 UTC, yu20201227 commented on keepYourFaceGreat/ViewController.swift
> -        // Do any additional setup after loading the view.
ありがとうございます！
すでにテストのプルリクで削除したから、ここの差分が再び出るのはおかしいということですよね？
ちなみに、テストのプルリクはマージする予定でした。

2020-12-08 15:37 UTC, fuchi0741 commented on keepYourFaceGreat/ViewController.swift
> -        // Do any additional setup after loading the view.
`すでにテストのプルリクで削除したから、ここの差分が再び出るのはおかしいということですよね？
`
差分がでるのはおかしくないです！
理由は、テストのプルリクの差分をこのブランチは知らないので、この差分がでるのは正常です！

2020-12-08 15:38 UTC, yu20201227 commented on Podfile
> +pod 'lottie-ios'
わかりました！
Rubyで書かれているんですね...
①修正方法は、直接podfileをいじって直せば良いでしょうか？
②インデント変更後は、新しいブランチでPRを出すということですか？

2020-12-08 15:38 UTC, fuchi0741 commented on keepYourFaceGreat/ViewController.swift
> -        // Do any additional setup after loading the view.
今回のコメントはテストのプルリクでコメント削除しているのであれば、今回の差分でコメント削除を再びする必要はないのでは？ということです！

2020-12-08 15:40 UTC, fuchi0741 commented on Podfile
> +pod 'lottie-ios'
> ①修正方法は、直接podfileをいじって直せば良いでしょうか？

ターミナルでも直接でもどっちでも大丈夫です！

> ②インデント変更後は、新しいブランチでPRを出すということですか？

あ、違います！
えっと、今回のブランチ上でそのまま修正をして、そのままpushすればこのPRのコミットが増えて修正が完了するという流れです！

2020-12-08 15:41 UTC, fuchi0741 commented on Podfile
> +pod 'lottie-ios'
なので同じブランチで修正可能ですね

2020-12-08 15:43 UTC, fuchi0741 commented on Podfile
> +pod 'lottie-ios'
Swift作った人はRubyを参考したって聞いたことがありますmm
なのでちょこちょこRubyはでてきますmm

2020-12-08 15:44 UTC, yu20201227 commented on Podfile
> +# platform :ios, '9.0'
なるほど！
二行目をアンコメントして、iosのサポート範囲を決めるということですね！
ちなみに、この場合だとios9.0までしかサポートしませんよという認識で正しいですか？

2020-12-08 15:47 UTC, fuchi0741 commented on Podfile
> +# platform :ios, '9.0'
> この場合だとios9.0までしかサポートしませんよという認識で正しいですか？
はい。iOS9以降しかサポートしないですよという意味です！

まあiOS13.0以上が全体の92%とからしいので13.0でいいのではと思っています。

2020-12-08 15:50 UTC, fuchi0741 commented on Podfile
> +# platform :ios, '9.0'
ちなみに今の案件はiOS11以上がサポート対象です

2020-12-09 03:45 UTC, yu20201227 commented on Podfile
> +pod 'lottie-ios'
こちら、同じブランチで修正完了です！
Ruby、覚えておきます！

2020-12-09 03:46 UTC, yu20201227 commented on Podfile
> +# platform :ios, '9.0'
こちら修正完了しました！
13.0に変更致しました。

2020-12-09 03:49 UTC, yu20201227 commented on keepYourFaceGreat/ViewController.swift
> -        // Do any additional setup after loading the view.
なるほど！そういうことですか！
正直、はっきりと原因がわかりません🙇‍♂️

2020-12-09 03:53 UTC, yu20201227 commented
> チケット追加依頼出しますー！
> READMEに使用ライブラリ一覧を作成
> 
> チケット作成とどこかのタイミングで実施お願いしますー！
> 
> 使用するライブラリを把握したいのでー！

・READMEも他と同様に新しいブランチを作成した上で、PRを出すという流れでOKですか？

2020-12-09 06:06 UTC, fuchi0741 commented on Podfile
> +pod 'lottie-ios'
Ruby使うのはpodfileくらいなので一旦無視で大丈夫です！

本格的にRubyが求められるときはFastlaneって技術を使用するときですね！
興味があれば調べて見てくださいー！

2020-12-09 06:07 UTC, fuchi0741 commented
> > チケット追加依頼出しますー！
> > READMEに使用ライブラリ一覧を作成
> > チケット作成とどこかのタイミングで実施お願いしますー！
> > 使用するライブラリを把握したいのでー！
> 
> ・READMEも他と同様に新しいブランチを作成した上で、PRを出すという流れでOKですか？

はい！そうです！

2020-12-09 06:08 UTC, fuchi0741 reviewed
@yu20201227 LGTM👍
git ignore や readmeは別途お願いしますー！

2020-12-09 06:08 UTC, fuchi0741 approved these changes

2020-12-09 06:09 UTC, fuchi0741 commented
指摘もたっらあとの修正のアクションができるようになったので、いい感じだなと思っています！

2020-12-09 07:13 UTC, yu20201227 commented
> 指摘もたっらあとの修正のアクションができるようになったので、いい感じだなと思っています！

ありがとうございます！！

2020-12-09 12:08 UTC, fuchi0741 commented on keepYourFaceGreat/ViewController.swift
> -        // Do any additional setup after loading the view.
> 正直、はっきりと原因がわかりません🙇‍♂️

developブランチからブランチを作成したと思うのですが、作成したときのdevelopブランチは
  // Do any additional setup after loading the view.
このコメントが残っているはずなのは伝わります？

2020-12-09 12:09 UTC, fuchi0741 commented
@yu20201227 マージOKですー！

2020-12-09 14:44 UTC, merged

2020-12-09 15:03 UTC, yu20201227 commented on keepYourFaceGreat/ViewController.swift
> -        // Do any additional setup after loading the view.
マージもされていないし、まだ何もいじっていないからということですか？