styroboardへの部品設置
yu20201227/KeepYourFaceGreat pull request #7
Opened 2020-12-12 01:23 UTC by yu20201227

## clone コマンド 
git clone -b feature/storyboard https://github.com/yu20201227/KeepYourFaceGreat.git

## Trello
storyboard作成

## 概要
一通りの部品を設置。
（今後変更の可能性はあるのでその際にまたPR)

## レビューで見て欲しいポイント
XMLでしっかりと差分が出ていること

## 参考URL

## 11 Pro や SEなど異なる端末でもレイアウトが崩れないか？
別チケット

## 期待通りの挙動をするか
OK 

## レビュー依頼
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741 

レビューお願いしますー！

## 補足
まだ骨組み状態という感じですが、このようになっています。
<img width="1280" alt="スクリーンショット 2020-12-12 10 18 31" src="https://user-images.githubusercontent.com/72218177/101968743-f8e33200-3c63-11eb-84b8-e970ad92623f.png">

2020-12-12 16:16 UTC, fuchi0741 commented
AutoLayoutでレイアウトを整えて欲しいです！
(端末で複数で試すとレイアウトが崩れてしまってます！)

あと部品を作った場合は以下の対応をPR内にお願いします！

- 対応するViewControllerを作成する
- 画面遷移をできるようにする(独立した画面をなくす)
- Outlet接続/Action接続を予めやっておく

2020-12-12 16:17 UTC, fuchi0741 commented
AutoLayoutちょっとヤバそうだったら声かけてください！
若干学習コストが高いかもなので！

あと設計でいくつか気になることがあるので、今後zoomしませんか？？

2020-12-12 16:18 UTC, fuchi0741 commented
@yu20201227 コメントしましたー１

2020-12-19 15:07 UTC, yu20201227 commented
あと部品を作った場合は以下の対応をPR内にお願いします！

対応するViewControllerを作成する
画面遷移をできるようにする(独立した画面をなくす)
Outlet接続/Action接続を予めやっておく

こちら３点、完了しました！
@fuchi0741

2020-12-20 12:21 UTC, fuchi0741 requested changes
@yu20201227 コメントしましたー！
わからない箇所があれば質問くださいー！

2020-12-20 12:21 UTC, fuchi0741 commented on keepYourFaceGreat/Controller/MorningPhotoViewController.swift
> +    @IBAction func toNightButton(_ sender: Any) {
接続のときの型なのですが、
Anyだと型(StringとかIntとかUIButtonとか)の指定がないとほぼ同義でSwiftっぽくないです、、！

なのでAnyではなく、UIButtonなどの型を指定するようにしましょう！

ex
`@IBAction func toNightButton(_ sender: UIButton) {   }`

今回に限らずAnyはなるべく避けるいう意識を持つといいと思いますー！

2020-12-20 12:21 UTC, fuchi0741 commented on keepYourFaceGreat/Controller/MorningPhotoViewController.swift
> +    @IBAction func toLibraryButton(_ sender: Any) {
@IBActionの命名はどのタイミングで呼ばれるかを明記するとわかりやすいですー！
ボタンをタップした後に{}の中身が呼ばれると思うので、

`didTap xxx` という命名の仕方をよく見るのでオススメです！
xxx は実際のどんな処理をするのか {} 内の処理が予想できる命名がベストですね！
命名において処理や中身が予想できるか？という視点は大事ですー！

今回のケースだと写真のライブラリに遷移するボタンだと思うので、
`didTapToLibraryButton
`
にするかなーと思いました！

Buttonという命名を入れているのがわかりやすくていいと思いました！
(storyboadをみなくてもButtonだと予想できるので、、！)

2020-12-22 06:28 UTC, closed without merging